/*
 *
 * Created: 10/3/2018 10:32:55 AM
 * Author : home
 */ 

//#define _AT328_ADC_EXTERN_VECT
//#define _AT328_UART_EXTERN_VECT
#define F_CPU 16000000
#define _AT328_ADC_FREEFLOW 1

#include <avr/io.h>
#include <util/delay.h>
#include "AT328UART.c"
#include "AT328ADC.c"
//#include "AT328OScope.c"

int main(void)
{
	AT328_UART_init();
	AT328_ADC_init();
	
	while (1)
	{
		_delay_ms(5000);
		AT328_UART_outs("AAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBBAAAAAAAAAABBBBBBBBBB");
	}
}

